{{- if .Values.mysql.enabled }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ include "elabftw.database.secretName" . }}

type: Opaque

stringData:
  username: {{ .Values.mysql.auth.username | quote }}
  password: {{ .Values.mysql.auth.password | quote }}

{{- end }}
