{{- if not .Values.elabftw.secrets.existingSecret }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ include "elabftw.secretName" . }}

type: Opaque

stringData:

  SECRET_KEY: {{ .Values.elabftw.secrets.secretKey | quote }}

{{- end }}
