name: Release Charts

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release charts
        uses: bitdeps/helm-oci-charts-releaser@v0.1.5
        with:
          oci_registry: ghcr.io/tugraz-rdm
          oci_username: ${{ github.actor }}
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
